name: Deploy React App
on: push
jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - name: Get the reposotory code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Test application
        run: npm run test
      - name: Lint application
        run: npm run lint
      - name: Build application
        run: npm run build
      - name: Deploy
        run: echo Deploying ...